spring.application.name=todolist

# Ativa a interface web para ver o banco de dados
spring.h2.console.enabled=true

# Define a URL amigável para acessar essa interface
spring.h2.console.path=/h2-console

# Mantém um nome fixo para o banco (facilita o login)
spring.datasource.url=jdbc:h2:mem:todolistdb